thecut/galleries/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from . import feeds, views
from django.conf.urls import include, url


urls = [

    url(r'^$',
        views.ListView.as_view(), name='gallery_list'),
    url(r'^(?P<page>\d+)$',
        views.ListView.as_view(), name='paginated_gallery_list'),
    url(r'^latest\.xml$',
        feeds.LatestGalleryFeed(), name='gallery_feed'),

    url(r'^categories/(?P<slug>[\w-]+)/$',
        views.ListView.as_view(), name='category_gallery_list'),
    url(r'^categories/(?P<slug>[\w-]+)/(?P<page>\d+)$',
        views.ListView.as_view(), name='paginated_category_gallery_list'),
    url(r'^categories/(?P<slug>[\w-]+)/latest\.xml$',
        feeds.LatestCategoryGalleryFeed(), name='category_gallery_feed'),

    url(r'^(?P<slug>[\w-]+)/$',
        views.MediaListView.as_view(), name='gallery_media_list'),
    url(r'^(?P<slug>[\w-]+)/(?P<page>\d+)$',
        views.MediaListView.as_view(), name='paginated_gallery_media_list'),

]

urlpatterns = [url(r'^', include(urls, namespace='galleries'))]

thecut/galleries/models.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from django.core.urlresolvers import reverse
from django.db import models
from thecut.publishing.models import Content, SiteContentWithSlug
from thecut.publishing.utils import generate_unique_slug


class AbstractGallery(SiteContentWithSlug):

    class Meta(SiteContentWithSlug.Meta):
        abstract = True
        ordering = ('-publish_at', 'title')
        verbose_name_plural = 'galleries'


class AbstractGalleryCategory(Content):

    slug = models.SlugField(unique=True)

    class Meta(Content.Meta):
        abstract = True
        verbose_name_plural = 'gallery categories'

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = generate_unique_slug(
                self.title, self.__class__.objects.all())
        return super(AbstractGalleryCategory, self).save(*args, **kwargs)


class Gallery(AbstractGallery):

    categories = models.ManyToManyField('galleries.GalleryCategory',
                                        related_name='galleries', blank=True,
                                        null=True)

    def get_absolute_url(self):
        return reverse('galleries:gallery_media_list',
                       kwargs={'slug': self.slug})


class GalleryCategory(AbstractGalleryCategory):

    def get_absolute_url(self):
        return reverse('galleries:category_gallery_list',
                       kwargs={'slug': self.slug})

thecut/galleries/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
from . import settings
from .models import Gallery, GalleryCategory
from django.shortcuts import get_object_or_404, redirect
from django.views import generic


class DetailView(generic.DetailView):

    context_object_name = 'gallery'
    model = Gallery
    template_name_field = 'template'

    def get_queryset(self, *args, **kwargs):
        queryset = super(DetailView, self).get_queryset(*args, **kwargs)
        return queryset.current_site().active()


class ListView(generic.ListView):

    context_object_name = 'gallery_list'
    model = Gallery
    paginate_by = settings.GALLERY_PAGINATE_BY

    def get(self, *args, **kwargs):
        page = self.kwargs.get('page', None)
        if page is not None and int(page) < 2:
            category = self.get_category()
            if category:
                return redirect('galleries:category_gallery_list',
                                slug=category.slug, permanent=True)
            else:
                return redirect('galleries:gallery_list', permanent=True)
        return super(ListView, self).get(*args, **kwargs)

    def get_category(self):
        if not hasattr(self, '_category'):
            slug = self.kwargs.get('slug', None)
            if slug is not None:
                category = get_object_or_404(GalleryCategory.objects.active(),
                                             slug=slug)
            else:
                category = None
            self._category = category
        return self._category

    def get_context_data(self, *args, **kwargs):
        context_data = super(ListView, self).get_context_data(*args, **kwargs)
        category = self.get_category()
        context_data.setdefault('category', category)
        return context_data

    def get_queryset(self, *args, **kwargs):
        queryset = super(ListView, self).get_queryset(*args, **kwargs)
        category = self.get_category()
        if category:
            queryset = queryset.filter(categories=category)
        return queryset.current_site().active()


class MediaListView(generic.ListView):

    context_object_name = 'gallery_media_list'
    paginate_by = settings.GALLERY_MEDIA_PAGINATE_BY
    template_name = 'galleries/gallery_media_list.html'
    template_name_field = 'template'
    _gallery = None

    def get_template_names(self, *args, **kwargs):
        """Select the template to render.

        Basic reimplementation of SingleObjectTemplateResponseMixin's
        get_template_name(). Renders with the gallery object's template
        property if it's set.
        """
        templates = super(MediaListView, self).get_template_names(
            *args, **kwargs)
        gallery = self.get_gallery()
        if gallery:
            model_template = getattr(gallery, self.template_name_field, None)
            if model_template:
                templates = [model_template] + templates
        return templates

    def get(self, *args, **kwargs):
        page = self.kwargs.get('page', None)
        if page is not None and int(page) < 2:
            return redirect('galleries:gallery_media_list',
                            slug=self.get_gallery().slug, permanent=True)
        return super(MediaListView, self).get(*args, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context_data = super(MediaListView, self).get_context_data(*args,
                                                                   **kwargs)
        context_data.update({'gallery': self.get_gallery()})
        return context_data

    def get_gallery(self):
        if self._gallery is None:
            self._gallery = get_object_or_404(
                Gallery.objects.current_site().active(),
                slug=self.kwargs.get('slug', None))
        return self._gallery

    def get_queryset(self, *args, **kwargs):
        return self.get_gallery().media.all()

thecut/galleries/templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
  
  <head>
    <title>{% block title %}{% endblock %}</title>
    {% block extrahead %}{% endblock %}
  </head>
  
  <body>
    {% block content %}
    {% endblock %}
  </body>
  
</html>

thecut/galleries/templates/galleries/base.html
{% extends "base.html" %}

thecut/galleries/templates/galleries/gallery_detail.html
{% extends "galleries/base.html" %}
{% load thumbnail %}

{% block title %}{{ gallery.title }} - {{ block.super }}{% endblock %}

{% block extrahead %}
  {{ block.super }}
  {% if not gallery.is_indexable %}<meta name="robots" content="noindex" />{% endif %}
  {% if gallery.meta_description %}<meta name="description" content="{{ gallery.meta_description }}" />{% endif %}
{% endblock %}

{% block content %}
  
  <h1>{{ gallery.heading }}</h1>
  {% if gallery.featured_content %}<div>{{ gallery.featured_content|safe }}</div>{% endif %}
  {% if gallery.content %}<div>{{ gallery.content|safe }}</div>{% endif %}
  
  {% spaceless %}{% for image in gallery.media.images %}
    {% if forloop.first %}<h2>Images</h2><ul>{% endif %}
    {% thumbnail image.get_image "200x200" as thumb %}
    <li><a href="{{ image.get_absolute_url }}"><img src="{{ thumb.url }}" alt="{{ image }}" /></a></li>
    {% endthumbnail %}
    {% if forloop.last %}</ul>{% endif %}
  {% endfor %}{% endspaceless %}
  
  {% spaceless %}{% for document in gallery.media.documents %}
    {% if forloop.first %}<h2>Documents</h2><ul>{% endif %}
    {% thumbnail document.get_image "200x200" as thumb %}
    <li><a href="{{ document.get_absolute_url }}"><img src="{{ thumb.url }}" alt="{{ document }}" /></a></li>
    {% endthumbnail %}
    {% if forloop.last %}</ul>{% endif %}
  {% endfor %}{% endspaceless %}
  
  {% spaceless %}{% for video in gallery.media.videos %}
    {% if forloop.first %}<h2>Videos</h2><ul>{% endif %}
    {% thumbnail document.get_image "200x200" as thumb %}
    <li><a href="{{ video.get_absolute_url }}"><img src="{{ thumb.url }}" alt="{{ video }}" /></a></li>
    {% empty %}
    <li><a href="{{ video.get_absolute_url }}">{{ video }}</a></li>
    {% endthumbnail %}
    {% if forloop.last %}</ul>{% endif %}
  {% endfor %}{% endspaceless %}
  
  {% spaceless %}{% for video in gallery.media.youtubevideos %}
    {% if forloop.first %}<h2>YouTube Videos</h2><ul>{% endif %}
    {% thumbnail document.get_image "200x200" as thumb %}
    <li><a href="{{ video.get_absolute_url }}"><img src="{{ thumb.url }}" alt="{{ video }}" /></a></li>
    {% empty %}
    <li><a href="{{ video.get_absolute_url }}">{{ video }}</a></li>
    {% endthumbnail %}
    {% if forloop.last %}</ul>{% endif %}
  {% endfor %}{% endspaceless %}
  
{% endblock %}

thecut/galleries/templates/galleries/gallery_list.html
{% extends "galleries/base.html" %}
{% load url from future %}
{% load thumbnail %}

{% block title %}{{ category|default:"Galleries" }} - {{ block.super }}{% endblock %}

{% block extrahead %}
  {{ block.super }}

  {% if category %}
    {% if not category.is_indexable %}<meta name="robots" content="noindex" />{% endif %}
    {% if category.meta_description %}<meta name="description" content="{{ category.meta_description }}" />{% endif %}
    <link rel="alternate" href="{% url "galleries:category_gallery_feed" category.slug %}" type="application/atom+xml" title="Latest {{ category }}" />
  {% else %}
    <link rel="alternate" href="{% url "galleries:gallery_feed" %}" type="application/atom+xml" title="Latest galleries" />
  {% endif %}

  {% if page_obj.paginator.num_pages > 1 %}{% spaceless %}
    {% if page_obj.has_previous %}
      {% if category %}
        <link rel="prev" href="{% if page_obj.previous_page_number == 1 %}{% url "galleries:category_gallery_list" slug=category.slug %}{% else %}{% url "galleries:paginated_category_gallery_list" slug=category.slug page=page_obj.previous_page_number %}{% endif %}" />
      {% else %}
        <link rel="prev" href="{% if page_obj.previous_page_number == 1 %}{% url "galleries:gallery_list" %}{% else %}{% url "galleries:paginated_gallery_list" page=page_obj.previous_page_number %}{% endif %}" />
      {% endif %}
    {% endif %}
    {% if page_obj.has_next %}
      {% if category %}
        <link rel="next" href="{% url "galleries:paginated_category_gallery_list" slug=category.slug page=page_obj.next_page_number %}" />
      {% else %}
        <link rel="next" href="{% url "galleries:paginated_gallery_list" page=page_obj.next_page_number %}" />
      {% endif %}
    {% endif %}
  {% endspaceless %}{% endif %}
{% endblock %}

{% block content %}

  <h1>{{ category|default:"Galleries" }}</h1>
  {% if category.featured_content %}<div>{{ category.featured_content }}</div>{% endif %}
  {% if category.content %}<div>{{ category.content|safe }}</div>{% endif %}

  {% for gallery in gallery_list %}
  {% if forloop.first %}<ul>{% endif %}
    <li>
      <a href="{{ gallery.get_absolute_url }}">
        {% thumbnail gallery.media.get_image "200x200" as thumb %}<img src="{{ thumb.url }}" alt="{{ gallery }}" />{% endthumbnail %}
        {{ gallery.publish_at }}
        {{ gallery }}
        {{ gallery.summary }}
      </a>
    </li>
  {% if forloop.last %}</ul>{% endif %}
  {% empty %}
    <p>No galleries to display.</p>
  {% endfor %}

  {% if page_obj.paginator.num_pages > 1 %}
  <div>
    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.

    {% if page_obj.has_previous %}
      {% if category %}
        <a href="{% if page_obj.previous_page_number == 1 %}{% url "galleries:category_gallery_list" slug=category.slug %}{% else %}{% url "galleries:paginated_category_gallery_list" slug=category.slug page=page_obj.previous_page_number %}{% endif %}" rel="previous">previous</a>
      {% else %}
        <a href="{% if page_obj.previous_page_number == 1 %}{% url "galleries:gallery_list" %}{% else %}{% url "galleries:paginated_gallery_list" page=page_obj.previous_page_number %}{% endif %}" rel="previous">previous</a>
      {% endif %}
    {% endif %}

    {% if page_obj.has_next %}
      {% if category %}
        <a href="{% url "galleries:paginated_category_gallery_list" category.slug page_obj.next_page_number %}" rel="next">next</a>
      {% else %}
        <a href="{% url "galleries:paginated_gallery_list" page_obj.next_page_number %}" rel="next">next</a>
      {% endif %}
    {% endif %}

  </div>
  {% endif %}

{% endblock %}

thecut/galleries/templates/galleries/gallery_media_list.html
{% extends "galleries/base.html" %}
{% load url from future %}
{% load thumbnail %}

{% block title %}{{ gallery.title }} - {{ block.super }}{% endblock %}

{% block extrahead %}
  {{ block.super }}
  {% if not gallery.is_indexable %}<meta name="robots" content="noindex" />{% endif %}
  {% if gallery.meta_description %}<meta name="description" content="{{ gallery.meta_description }}" />{% endif %}

  {% if page_obj.paginator.num_pages > 1 %}{% spaceless %}
    {% if page_obj.has_previous %}
      <link rel="prev" href="{% if page_obj.previous_page_number == 1 %}{% url "galleries:gallery_media_list" gallery.slug %}{% else %}{% url "galleries:paginated_gallery_media_list" gallery.slug page_obj.previous_page_number %}{% endif %}" />
    {% endif %}
    {% if page_obj.has_next %}
      <link rel="next" href="{% url "galleries:paginated_gallery_media_list" gallery.slug page_obj.next_page_number %}" />
    {% endif %}
  {% endspaceless %}{% endif %}
{% endblock %}

{% block content %}

  <h1>{{ gallery.heading }}</h1>
  {% if gallery.featured_content %}<div>{{ gallery.featured_content|safe }}</div>{% endif %}
  {% if gallery.content %}<div>{{ gallery.content|safe }}</div>{% endif %}

  {% spaceless %}{% for media in gallery_media_list %}
  {% with media.content_object as item %}
  {% if forloop.first %}<h2>Media</h2><ul>{% endif %}
    {% thumbnail item.get_image "200x200" as thumb %}
    <li class="{{ media.content_type.model }}"><a href="{{ item.get_absolute_url }}"><img src="{{ thumb.url }}" alt="{{ item }}" /></a></li>
    {% endthumbnail %}
  {% if forloop.last %}</ul>{% endif %}
  {% endwith %}
  {% endfor %}{% endspaceless %}

  {% if page_obj.paginator.num_pages > 1 %}
  <div>
    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    {% if page_obj.has_previous %}<a href="{% if page_obj.previous_page_number == 1 %}{% url "galleries:gallery_media_list" gallery.slug %}{% else %}{% url "galleries:paginated_gallery_media_list" gallery.slug page_obj.previous_page_number %}{% endif %}" rel="previous">previous</a>{% endif %}
    {% if page_obj.has_next %}<a href="{% url "galleries:paginated_gallery_media_list" gallery.slug page_obj.next_page_number %}" rel="next">next</a>{% endif %}
  </div>
  {% endif %}

{% endblock %}